name: xvideos-download

on:
  push:
    branches:
      - release/1.0.0

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker build -t xvideos-download .
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker tag xvideos-download abplanning/xvideos-download:latest
            docker push abplanning/xvideos-download:latest
            docker rm -f xvideos-download
            docker run -d --name xvideos-download -p 8000:8000 abplanning/xvideos-download